Create user
wyncode/c39_cln_alt pull request #22
Opened 2020-11-22 22:42 UTC by kristinadurant

closes issue #21

2020-11-23 00:35 UTC, Stommy123 commented on client/src/components/Login.jsx
> +      console.log(response.data.user);
could we remove these console logs?

2020-11-23 00:36 UTC, Stommy123 commented on client/src/components/ProductPage.jsx
> +  console.log(tab1);
hmmm is this the same file from the previous PR? i think you should rebase with that branch after its merged to remove any duplicate code

2020-11-23 00:36 UTC, Stommy123 commented on client/src/components/Reviews.jsx
> +  let { id } = useParams();
same comment as on https://github.com/wyncode/c39_bike_shop/pull/32

2020-11-23 00:36 UTC, Stommy123 commented on client/src/components/ResetPassword.jsx
> +      console.log('Email sent');
could we remove this please?

2020-11-23 00:37 UTC, Stommy123 commented on client/src/components/ResetPassword.jsx
> +      setPopSignUp('updatePassword');
hmm i thought we discussed not redirecting to update password?

2020-11-23 00:37 UTC, Stommy123 commented on client/src/components/Profile.jsx
> +  console.log(currentUser);
couldwe remove this please

2020-11-23 00:37 UTC, Stommy123 commented on client/src/components/ResetPassword.jsx
> +      setPopSignUp('updatePassword');
since the backend will handle the redirecting

2020-11-23 00:37 UTC, Stommy123 commented on client/src/components/SignUp.jsx
> +      console.log(formData);
same comment here about console logs

2020-11-23 00:39 UTC, Stommy123 requested changes
Overall this is pretty solid. I just have some concerns about the duplication from the previous PR, and mainly with what we do after they user submits the reset password form. I don't think we should trigger the update password modal, this should be handled by the email link / backend route as discussed, right?

2020-11-23 01:43 UTC, kristinadurant commented on client/src/components/Login.jsx
> +      console.log(response.data.user);
sorry!!

2020-11-23 01:46 UTC, kristinadurant commented on client/src/components/Reviews.jsx
> +  let { id } = useParams();
I didn't get this, cause I am using the params to display the reviews. Is that what you were referring to?

2020-11-23 01:47 UTC, kristinadurant commented on client/src/components/Profile.jsx
> +  console.log(currentUser);
Of course 👍

2020-11-23 01:48 UTC, kristinadurant commented on client/src/components/ResetPassword.jsx
> +      setPopSignUp('updatePassword');
I need help understanding this redirecting.

2020-11-23 20:24 UTC, Amandat97 approved these changes

2020-11-23 22:07 UTC, ErnieAtLYD commented
Hi @kristinadurant - trying to help out with some PRs. I've been saying this to a lot of students but as a reminder: many smaller PR branches > 1 giant PR branch

2020-11-23 22:08 UTC, ErnieAtLYD commented on client/src/components/ResetPassword.jsx
> +      setPopSignUp('updatePassword');
I'm going to mark this as unresolved because after talking with Kristina it looks like Kristina and Amanda will be working with Tommy tonight. :+1:

2020-11-24 01:56 UTC, kristinadurant commented on client/src/components/ResetPassword.jsx
> +      setPopSignUp('updatePassword');
We fixed the issue of changing the password? Can we merge this PR now?

2020-11-25 00:10 UTC, naaltunian approved these changes

2020-11-25 00:11 UTC, merged